services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - homelab-network
    volumes:
      - ./data:/data
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_TTL=3600
      - REDIS_ENABLED=true
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - homelab-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - homelab-network
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL="http://backend:5000"

networks:
  homelab-network:


volumes:
  redis-data: