receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: homelab
    const_labels:
      app: "homelab-api"
  
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]